### ISSUE TITLE
BUG: ISAN 2.5.3 wont reboot only says ISAN2 OFFLINE

### ISSUE THREAD

**Issue by Ebojager** [Collective-SB/ISAN#51] opened 2021-09-26 19:24 UTC
**Describe the bug**
ISAN 2.5.3 wont work on my ship, no matter how many times Ive copied and verified fields. 
When I delete the field on the "_" Panel it just says the same thing "ISAN2 OFFLINE"

**To Reproduce**
1. Copy code from PDF to Advanced YOLOL chip and insert in Rack
2. Verify fields on previous mono v2 installed devices (Receiver A, AT and 180, and TextPanel named "_")
3. View TextPanel names "_"

**Expected behavior**
Reboot to a working ISAN v2.5.3

**Screenshots**

**Additional context**
I have come from a perfectly working v2 setup that even after reverting back using the same devices and chip, works fine.
I was even able to get "faultstarbase's" Simple Odometer to work with v2, but cant even get v2.5.3 to boot up. I have no other modules installed.
My current YOLOL are:
Default Generator script for Laborer II
Mining Laser Pulse
Mining Laser Sweep
Asteroid Avoidance
Resources/Status 
InsideSafeZone with Warning Button
Diagnostic / System Normal
Fuel and Gas Time Remaining
The only Advanced chip is the one for ISAN

**Comment by Ebojager** [comment] 2021-09-27 14:32
Found someone on Reddit said this:
“I have the same problem. I don't know what causes it, but commenting line 20 out forces it to show coordinates. I believe this completely disables the ability to turn it off though.  Isn't a problem for me as I never stream.”

**Comment by Azurethi** [comment] 2022-07-10 02:02
This has been addressed multiple times over discord, feel free to contact me there for help. 

Closing, user error, not a bug

**Closed by Azurethi** 2022-07-10 02:02 UTC
Labels: bug
